# Generated by Django 6.1 on 2026-08-29 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_swift_bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account_resolved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='app.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('local', 'Local'), ('external', 'External (domestic)'), ('international', 'International')], default='local', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.CharField(blank=True, default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accounts', to='app.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.userbankaccount'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transfer_type', 'created_at'], name='app_transac_transfe_a44633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbankaccount',
            unique_together={('user', 'bank', 'account_number')},
        ),
    ]
